// mockLocations.js
export const locations = [
    {
      title: "南湾里, Taiwan",
      host: "Mis. Cat",
      price: "630",
      totalCost: "6,297",
    },
    {
      title: "Hengchun Township, Taiwan",
      host: "Christina Victoria",
      price: "5,705",
      totalCost: "57,045",
    },
    {
      title: "Hengchun Township, Taiwan",
      host: "Vivienne",
      price: "223",
      totalCost: "2,233",
    },
    {
      title: "Hengchun Township, Taiwan",
      host: "Shining-One",
      price: "549",
      totalCost: "5,488",
    },
    {
      title: "Hengchun Township, Taiwan",
      host: "Vivienne",
      price: "140",
      totalCost: "1,396",
    },
    {
        title: "南湾里, Taiwan",
        host: "Mis. Cat",
        price: "630",
        totalCost: "6,297",
      },
      {
        title: "Hengchun Township, Taiwan",
        host: "Christina Victoria",
        price: "5,705",
        totalCost: "57,045",
      },
      {
        title: "Hengchun Township, Taiwan",
        host: "Vivienne",
        price: "223",
        totalCost: "2,233",
      },
      {
        title: "Hengchun Township, Taiwan",
        host: "Shining-One",
        price: "549",
        totalCost: "5,488",
      },
      {
        title: "Hengchun Township, Taiwan",
        host: "Vivienne",
        price: "140",
        totalCost: "1,396",
      },
      {
        title: "南湾里, Taiwan",
        host: "Mis. Cat",
        price: "630",
        totalCost: "6,297",
      },
      {
        title: "Hengchun Township, Taiwan",
        host: "Christina Victoria",
        price: "5,705",
        totalCost: "57,045",
      },
      {
        title: "Hengchun Township, Taiwan",
        host: "Vivienne",
        price: "223",
        totalCost: "2,233",
      },
      {
        title: "Hengchun Township, Taiwan",
        host: "Shining-One",
        price: "549",
        totalCost: "5,488",
      },
      {
        title: "Hengchun Township, Taiwan",
        host: "Vivienne",
        price: "140",
        totalCost: "1,396",
      },
      {
        title: "南湾里, Taiwan",
        host: "Mis. Cat",
        price: "630",
        totalCost: "6,297",
      },
      {
        title: "Hengchun Township, Taiwan",
        host: "Christina Victoria",
        price: "5,705",
        totalCost: "57,045",
      },
      {
        title: "Hengchun Township, Taiwan",
        host: "Vivienne",
        price: "223",
        totalCost: "2,233",
      },
      {
        title: "Hengchun Township, Taiwan",
        host: "Shining-One",
        price: "549",
        totalCost: "5,488",
      },
      {
        title: "Hengchun Township, Taiwan",
        host: "Vivienne",
        price: "140",
        totalCost: "1,396",
      },
      {
        title: "南湾里, Taiwan",
        host: "Mis. Cat",
        price: "630",
        totalCost: "6,297",
      },
      {
        title: "Hengchun Township, Taiwan",
        host: "Christina Victoria",
        price: "5,705",
        totalCost: "57,045",
      },
      {
        title: "Hengchun Township, Taiwan",
        host: "Vivienne",
        price: "223",
        totalCost: "2,233",
      },
      {
        title: "Hengchun Township, Taiwan",
        host: "Shining-One",
        price: "549",
        totalCost: "5,488",
      },
      {
        title: "Hengchun Township, Taiwan",
        host: "Vivienne",
        price: "140",
        totalCost: "1,396",
      },
      {
        title: "南湾里, Taiwan",
        host: "Mis. Cat",
        price: "630",
        totalCost: "6,297",
      },
      {
        title: "Hengchun Township, Taiwan",
        host: "Christina Victoria",
        price: "5,705",
        totalCost: "57,045",
      },
      {
        title: "Hengchun Township, Taiwan",
        host: "Vivienne",
        price: "223",
        totalCost: "2,233",
      },
      {
        title: "Hengchun Township, Taiwan",
        host: "Shining-One",
        price: "549",
        totalCost: "5,488",
      },
      {
        title: "Hengchun Township, Taiwan",
        host: "Vivienne",
        price: "140",
        totalCost: "1,396",
      },
      {
        title: "南湾里, Taiwan",
        host: "Mis. Cat",
        price: "630",
        totalCost: "6,297",
      },
      {
        title: "Hengchun Township, Taiwan",
        host: "Christina Victoria",
        price: "5,705",
        totalCost: "57,045",
      },
      {
        title: "Hengchun Township, Taiwan",
        host: "Vivienne",
        price: "223",
        totalCost: "2,233",
      },
      {
        title: "Hengchun Township, Taiwan",
        host: "Shining-One",
        price: "549",
        totalCost: "5,488",
      },
      {
        title: "Hengchun Township, Taiwan",
        host: "Vivienne",
        price: "140",
        totalCost: "1,396",
      },
      {
        title: "南湾里, Taiwan",
        host: "Mis. Cat",
        price: "630",
        totalCost: "6,297",
      },
      {
        title: "Hengchun Township, Taiwan",
        host: "Christina Victoria",
        price: "5,705",
        totalCost: "57,045",
      },
      {
        title: "Hengchun Township, Taiwan",
        host: "Vivienne",
        price: "223",
        totalCost: "2,233",
      },
      {
        title: "Hengchun Township, Taiwan",
        host: "Shining-One",
        price: "549",
        totalCost: "5,488",
      },
      {
        title: "Hengchun Township, Taiwan",
        host: "Vivienne",
        price: "140",
        totalCost: "1,396",
      },
  ];
  